# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

run:
  timeout: 5m
  modules-download-mode: readonly


linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
    - gofmt
    - govet
    - staticcheck
  settings:
    govet:
      disable-all: true
      enable:
        # Check for missing values after append.
        - printf 

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0