// license that can be found in the LICENSE file.

// Code generated by "codegen -type=int"; DO NOT EDIT.

package code

// init register error codes defines in this source code to `imooc/mxshop/pkg/errors`
func init() {
	register(ErrUserNotFound, 404, "User not found")
}
