log:
  name: "dailyyourgo-user-srv" # logger 名称。
  development: true # 是否开启开发模式。，开发模式下会打印调试信息，默认 false。
  level: "debug" # 日志级别，优先级从低到高依次为：debug，info，warn，error，dpanic，panic，fatal。
  format: "console" # 支持的日志输出格式，目前支持 console 和 json 两种。console 其实就是 text 格式。
  enable-color: true # 是否开启颜色输出，true：是，false：否
  disable-caller: false # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件、函数和行号
  disable-stacktrace: false # 是否在 panic 及以上级别禁止打印堆栈信息
  output-paths: logs/dailyyourgo-user-srv.log,stdout # 支持输出到多个输出，逗号分开。支持输出到标准输出（stdout）和文件
  error-output-paths: logs/dailyyourgo-user-srv.error.log # zap 内部（非业务）错误日志输出路径，多个输出，逗号分开