log:
  name: "dailyyourgo-user-srv" # logger 名称。
  development: true # 是否开启开发模式。，开发模式下会打印调试信息，默认 false。
  level: "debug" # 日志级别，优先级从低到高依次为：debug，info，warn，error，dpanic，panic，fatal。
  format: "console" # 支持的日志输出格式，目前支持 console 和 json 两种。console 其实就是 text 格式。
  enable-color: true # 是否开启颜色输出，true：是，false：否
  disable-caller: false # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件、函数和行号
  disable-stacktrace: false # 是否在 panic 及以上级别禁止打印堆栈信息
  output-paths: logs/dailyyourgo-user-srv.log,stdout # 支持输出到多个输出，逗号分开。支持输出到标准输出（stdout）和文件
  error-output-paths: logs/dailyyourgo-user-srv.error.log # zap 内部（非业务）错误日志输出路径，多个输出，逗号分开
registry:
  address: "192.168.5.52:8500"
  scheme: "http"
server:
  enable-health-check: true
  enable-profiling: true
  enable-metrics: true
  enable-limit: true
  host: "192.168.5.52"
  port: 8079
  http-port: 8080
  name: "daily-your-go-user-srv" 
telemetry:
  name: "daily-your-go-user-srv"
  Endpoint: "http://192.168.5.52:14268/api/traces"
  Sampler: 1.0
  Batcher: "jaeger"
# MySQL 数据库相关配置
mysql:
  host: "192.168.5.52" # MySQL 机器 IP，默认 127.0.0.1
  port: "3307" # MySQL 端口，默认 3306
  username: "root" # MySQL 用户名（建议授权最小权限集），默认 ""
  password: "123456" # MySQL 密码，默认 ""
  database: "mxshop_user_srv" # iam 系统所用的数据库名
  max-idle-connections: 100 # MySQL 最大空闲连接数，默认 100
  max-open-connections: 100 # MySQL 最大连接数，默认 100
  max-connection-life-time: 10s # 空闲连接最大存活时间，默认 10s
  log-level: 4 # GORM log level， 1：slient, 2: error 3: warn 4: info
nacos:
  host: "192.168.5.52"
  port: 8848
  namespace: "public"
  user: "nacos"
  password: "nacos"
  dataid: "flow"
  group: "sentinel-go"
   